name: Build Images

on:
  push:
    branches: 
      - '**'    # matches every branch
      - '*/*'   # matches every branch containing a single '/'
      - '*'     # matches every branch
#      - '!master' # excludes master
  pull_request:
    branches: 
      [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List and Read files
        run: |
              ls -ltra
              cat README.md